[package]
name = "frameplay"
description = "Simple frame repeater (Library)"

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []

async-tokio = ["tokio"]

[dependencies]
tokio = { version = "1", features = ["io-std", "sync", "time"], optional = true }

[workspace]
members = ["cli"]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Charles Dong <chardon_cs@proton.me>"]
repository = "https://github.com/chardoncs/frameplay.git"
license = "MIT"
